# This file can only be edited inside the uBlue image's git repository.

# The image will be at "ghcr.io/yourusername/name".
name: swayfx-blue-personal
# The native container image to build on top of.
# Warning: Non-uBlue images might not work properly, due to missing components.
base-image: ghcr.io/ublue-os/base-main
# What Fedora version to use. Use an explicit version or `latest`.
# If you use `latest`, you will be automatically updated to the next major
# Fedora version, assuming the image you're using as your base container
# builds with the tag (all uBlue images do this).
fedora-version: 38
# This description will be visible in the container metadata.
description: A starting point for further customization of uBlue images. Make your own! https://universal-blue.org/tinker/make-your-own/
# These scripts will be executed during the container build.
# Place scripts in the "scripts/" dir and put the corresponding filenames here.
# Any files that aren't listed here won't be executed automatically, which
# means that you can place "helper" or "library" scripts in the folder too.
# You can use "autorun.sh" if you want an automatic runner.
scripts:
  # "Pre" scripts run very early in the build, immediately after your custom
  # repos have been imported (so that you can access those repos if necessary).
  pre:
    # Automatically runs script files within "scripts/pre/".
    - autorun.sh
    # Manually listed scripts.
    # - example_pre.sh
  # "Post" scripts run at the end of the build process.
  post:
    # Automatically runs script files within "scripts/post/".
    - autorun.sh
    # Manually listed scripts.
    # - example_post.sh
# Custom RPM configuration.
# These changes will be integrated into your custom image at the "system level".
rpm:
  # A list of urls of ".repo" files that should be added to your system.
  # This is the proper way to add custom COPR repos to your image.
  # Tip: Use `%FEDORA_VERSION%` instead of static Fedora version numbers,
  # so that your repos automatically use your image's actual Fedora version,
  # which greatly simplifies future maintenance of your custom recipe.
  repos:
    # Example (which also demonstrates version number expansion):
    # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%FEDORA_VERSION%/atim-starship-fedora-%FEDORA_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/swayfx/swayfx/repo/fedora-38/swayfx-swayfx-fedora-38.repo
  - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-38/tofik-nwg-shell-fedora-38.repo
  - https://flathub.org/repo/flathub.flatpakrepo
  - https://copr.fedorainfracloud.org/coprs/patrickl/yabridge/repo/fedora-38/patrickl-yabridge-fedora-38.repo
  - https://raw.githubusercontent.com/Luiza1011/swayfx-blue-personal/live/vivaldi.repo
  - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-38/erikreider-SwayNotificationCenter-fedora-38.repo
  - https://copr.fedorainfracloud.org/coprs/lchh/navidrome/repo/fedora-38/lchh-navidrome-fedora-38.repo
  - https://copr.fedorainfracloud.org/coprs/luiza1011/Lu-dotfiles/repo/fedora-38/luiza1011-Lu-dotfiles-fedora-38.repo
  
  # These RPMs will be installed from your enabled repositories (Fedora's own
  # repos, extra "repos" you've added, etc). The installation is automatically
  # performed via rpm-ostree during the image build, and will be pre-installed
  # at the "system level" in the final image.
  install:
    - python-pip
    - libadwaita
    - unrar
    - p7zip 
    - p7zip-plugins
    - terminator
    - swayfx
    - rofi
    - neovim
    - pavucontrol
    - blueman
    - htop
    - mc
    - fastfetch
    - nemo
    - nemo-fileroller
    - nwg-drawer
    - nwg-look
    - zsh
    - tmux
    - zsh-autosuggestions
    - waybar
    - network-manager-applet
    - grim
    - pulseaudio
    - pulseaudio-libs
    - pamixer
    - playerctl
    - polkit-gnome
    - swaync
    - rust
    - cargo
    - steam-devices
    - sddm
    - firewall-config
    - noip
    - mediawriter
    - lu-blue
    - vivaldi

remove:
    - firefox
    - firefox-langpacks
